<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>FelLib</RootNamespace>
    <NoWarn>$(NoWarn);CS0618;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hakchi.Usb\Hakchi.Usb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibUsbDotNet" Version="2.2.29" />
  </ItemGroup>

</Project>
