<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Hakchi.Rndis</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hakchi.Usb\Hakchi.Usb.csproj" />
    <PackageReference Include="LibUsbDotNet" Version="2.2.85" />
  </ItemGroup>
</Project>
